### ISSUE TITLE
R-CMD-check fails?

### ISSUE THREAD

**Issue by giabaio** [n8thangreen/BCEA#147]
Please briefly describe your problem and what output you expect. If you have a general question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

The `R-CMD-check` fails in your fork. But I *think* it should be OK with the changes I've added [here](https://github.com/giabaio/BCEA/tree/dev). Does this help?

**Comment by n8thangreen** [comment]
🚀
