### ISSUE TITLE
include `label.pos` in latest version

### ISSUE THREAD

**Issue by n8thangreen** [n8thangreen/BCEA#159]
@giabaio I found the code that's missing:
https://github.com/n8thangreen/BCEA/blob/94e00201064d48f3505ad0e00bd9fa3da8c63ee4/R/ceplane.plot.R#L479

So it sticks the `k-...` next to the wtp line at minimum x-axis value as long as it doesn't go off the bottom of the plot. Shouldn't be difficult to add this back in.

**Comment by giabaio** [comment]
Thank you!


---
Gianluca Baio
Professor of Statistics and Health Economics | Head of Department


Department of Statistical Science | University College London
1-19 Torrington Place, London, WC1E 6BT, UK
Mastodon: @***@***.***_UCL> | Twitter: @stats_ucl<https://twitter.com/stats_UCL> | Instagram: @stats_UCL<https://instagram.com/ucl.stats/>


Telephone: +44(0)20 7679 1248 (internal: 41248)
Website: http://www.homepages.ucl.ac.uk/~ucakgba
Blog: https://gianluca.statistica.it/blog/
Book a meeting with me: https://book.morgen.so/gianlucabaio/book-me


***@***.***>   [https://www.svgrepo.com/show/157815/twitter.svg] <https://twitter.com/gianlubaio>    [https://www.svgrepo.com/show/138936/linkedin.svg] <https://www.linkedin.com/in/gianluca-baio-b893879/>    [https://www.svgrepo.com/show/341847/github.svg] <https://github.com/giabaio>    [https://www.geol.umd.edu/styles/academicons-192/svg/arxiv.svg] <https://arxiv.org/a/baio_g_1.html>    [https://www.geol.umd.edu/styles/academicons-192/svg/orcid.svg] <https://orcid.org/0000-0003-4314-2570>    [https://www.svgrepo.com/show/40973/soundcloud.svg] <https://soundcloud.com/uclsound/sets/sample-space>

_____________________________________________

For Head of Department correspondence, please use ***@***.******@***.***>

[https://s1g.s3.amazonaws.com/3f32ef1962be41fb8943ee58d28cf3aa.png]

This email may reach you outside of your working hours. If that’s the case, please do not feel pressure to reply immediately.
________________________________
From: Dr Nathan Green ***@***.***>
Sent: 29 December 2024 12:59
To: n8thangreen/BCEA ***@***.***>
Cc: Baio, Gianluca ***@***.***>; Mention ***@***.***>
Subject: [n8thangreen/BCEA] include `label.pos` in latest version (Issue #159)


⚠ Caution: External sender


@giabaio<https://github.com/giabaio> I found the code that's missing:
https://github.com/n8thangreen/BCEA/blob/94e00201064d48f3505ad0e00bd9fa3da8c63ee4/R/ceplane.plot.R#L479

So it sticks the k-... next to the wtp line at minimum x-axis value as long as it doesn't go off the bottom of the plot. Shouldn't be difficult to add this back in.

**Comment by n8thangreen** [comment]
closed by c7351e491f55afa86116632338a4b583268d4a41

**Comment by giabaio** [comment]
[like]  Baio, Gianluca reacted to your message:
________________________________
