### ISSUE TITLE
Vignette signposting

### ISSUE THREAD

**Issue by rowlandseymour** [n8thangreen/BCEA#98]
There are quite a few vignettes and I think there needs to be some signposting for the user when they arrive at the package about what vignettes to look at first or which vignettes to use for particular tasks. This could be in the README or elsewhere. Some of the vignettes appear to be incomplete and I think these either need completing or removing from the JOSS branch of the repository. 

https://github.com/openjournals/joss-reviews/issues/4206

**Comment by n8thangreen** [comment]
Closes 8e17dcfb79dde4e5b9c7e086cb0e68a65a76bb6c
